var JOURNAL = [
  {"events":["cenoura","atividade física","final de semana"],"esquilo":false},
  {"events":["pão","pudim","escovou os dentes","final de semana","árvore"],"esquilo":false},
  {"events":["cenoura","nachos","escovou os dentes","pedalou","final de semana"],"esquilo":false},
  {"events":["brussel sprouts","sorvetem","escovou os dentes","computador","final de semana"],"esquilo":false},
  {"events":["potatoes","doce","escovou os dentes","atividade física","final de semana","dentist"],"esquilo":false},
  {"events":["brussel sprouts","pudim","escovou os dentes","running","final de semana"],"esquilo":false},
  {"events":["pizza","escovou os dentes","computador","trabalhou","árvore"],"esquilo":false},
  {"events":["pão","beer","escovou os dentes","pedalou","trabalhou"],"esquilo":false},
  {"events":["couve-flor","escovou os dentes","trabalhou"],"esquilo":false},
  {"events":["pizza","escovou os dentes","pedalou","trabalhou"],"esquilo":false},
  {"events":["lasagna","nachos","escovou os dentes","trabalhou"],"esquilo":false},
  {"events":["escovou os dentes","final de semana","árvore"],"esquilo":false},
  {"events":["alface","escovou os dentes","television","final de semana"],"esquilo":false},
  {"events":["spaghetti","escovou os dentes","trabalhou"],"esquilo":false},
  {"events":["escovou os dentes","computador","trabalhou"],"esquilo":false},
  {"events":["alface","nachos","escovou os dentes","trabalhou"],"esquilo":false},
  {"events":["cenoura","escovou os dentes","running","trabalhou"],"esquilo":false},
  {"events":["escovou os dentes","trabalhou"],"esquilo":false},
  {"events":["couve-flor","reading","final de semana"],"esquilo":false},
  {"events":["pão","escovou os dentes","final de semana"],"esquilo":false},
  {"events":["lasagna","escovou os dentes","atividade física","trabalhou"],"esquilo":false},
  {"events":["spaghetti","escovou os dentes","reading","trabalhou"],"esquilo":false},
  {"events":["cenoura","sorvetem","escovou os dentes","television","trabalhou"],"esquilo":false},
  {"events":["spaghetti","nachos","trabalhou"],"esquilo":false},
  {"events":["couve-flor","sorvetem","escovou os dentes","pedalou","trabalhou"],"esquilo":false},
  {"events":["spaghetti","amendoim","computador","final de semana"],"esquilo":true},
  {"events":["potatoes","sorvetem","escovou os dentes","computador","final de semana"],"esquilo":false},
  {"events":["potatoes","sorvetem","escovou os dentes","trabalhou"],"esquilo":false},
  {"events":["amendoim","escovou os dentes","running","trabalhou"],"esquilo":false},
  {"events":["potatoes","atividade física","trabalhou"],"esquilo":false},
  {"events":["pizza","sorvetem","computador","trabalhou"],"esquilo":false},
  {"events":["lasagna","sorvetem","trabalhou"],"esquilo":false},
  {"events":["couve-flor","doce","reading","final de semana"],"esquilo":false},
  {"events":["lasagna","nachos","escovou os dentes","running","final de semana"],"esquilo":false},
  {"events":["potatoes","escovou os dentes","trabalhou"],"esquilo":false},
  {"events":["cenoura","trabalhou"],"esquilo":false},
  {"events":["pizza","beer","trabalhou","dentist"],"esquilo":false},
  {"events":["lasagna","pudim","pedalou","trabalhou"],"esquilo":false},
  {"events":["spaghetti","escovou os dentes","reading","trabalhou"],"esquilo":false},
  {"events":["spaghetti","pudim","television","final de semana"],"esquilo":false},
  {"events":["pão","escovou os dentes","atividade física","final de semana"],"esquilo":false},
  {"events":["lasagna","amendoim","trabalhou"],"esquilo":true},
  {"events":["pizza","trabalhou"],"esquilo":false},
  {"events":["potatoes","atividade física","trabalhou"],"esquilo":false},
  {"events":["escovou os dentes","atividade física","trabalhou"],"esquilo":false},
  {"events":["spaghetti","escovou os dentes","television","trabalhou"],"esquilo":false},
  {"events":["pizza","pedalou","final de semana"],"esquilo":false},
  {"events":["cenoura","escovou os dentes","final de semana"],"esquilo":false},
  {"events":["cenoura","beer","escovou os dentes","trabalhou"],"esquilo":false},
  {"events":["pizza","amendoim","doce","trabalhou"],"esquilo":true},
  {"events":["cenoura","amendoim","escovou os dentes","reading","trabalhou"],"esquilo":false},
  {"events":["potatoes","amendoim","escovou os dentes","trabalhou"],"esquilo":false},
  {"events":["cenoura","nachos","escovou os dentes","atividade física","trabalhou"],"esquilo":false},
  {"events":["pizza","amendoim","escovou os dentes","television","final de semana"],"esquilo":false},
  {"events":["lasagna","escovou os dentes","pedalou","final de semana"],"esquilo":false},
  {"events":["couve-flor","amendoim","escovou os dentes","computador","trabalhou","árvore"],"esquilo":false},
  {"events":["alface","escovou os dentes","television","trabalhou"],"esquilo":false},
  {"events":["potatoes","escovou os dentes","computador","trabalhou"],"esquilo":false},
  {"events":["pão","doce","trabalhou"],"esquilo":false},
  {"events":["potatoes","nachos","trabalhou"],"esquilo":false},
  {"events":["cenoura","pudim","escovou os dentes","final de semana"],"esquilo":false},
  {"events":["cenoura","escovou os dentes","atividade física","final de semana","árvore"],"esquilo":false},
  {"events":["brussel sprouts","running","trabalhou"],"esquilo":false},
  {"events":["escovou os dentes","trabalhou"],"esquilo":false},
  {"events":["alface","escovou os dentes","running","trabalhou"],"esquilo":false},
  {"events":["doce","escovou os dentes","trabalhou"],"esquilo":false},
  {"events":["brussel sprouts","escovou os dentes","computador","trabalhou"],"esquilo":false},
  {"events":["pão","escovou os dentes","final de semana"],"esquilo":false},
  {"events":["couve-flor","escovou os dentes","final de semana"],"esquilo":false},
  {"events":["spaghetti","doce","television","trabalhou","árvore"],"esquilo":false},
  {"events":["cenoura","pudim","escovou os dentes","trabalhou"],"esquilo":false},
  {"events":["alface","escovou os dentes","trabalhou"],"esquilo":false},
  {"events":["cenoura","sorvetem","escovou os dentes","pedalou","trabalhou"],"esquilo":false},
  {"events":["pizza","escovou os dentes","trabalhou"],"esquilo":false},
  {"events":["spaghetti","amendoim","atividade física","final de semana"],"esquilo":true},
  {"events":["pão","beer","computador","final de semana","árvore"],"esquilo":false},
  {"events":["escovou os dentes","running","trabalhou"],"esquilo":false},
  {"events":["alface","amendoim","escovou os dentes","trabalhou","árvore"],"esquilo":false},
  {"events":["lasagna","escovou os dentes","television","trabalhou"],"esquilo":false},
  {"events":["couve-flor","escovou os dentes","running","trabalhou"],"esquilo":false},
  {"events":["cenoura","escovou os dentes","running","trabalhou"],"esquilo":false},
  {"events":["cenoura","reading","final de semana"],"esquilo":false},
  {"events":["cenoura","amendoim","reading","final de semana"],"esquilo":true},
  {"events":["potatoes","escovou os dentes","running","trabalhou"],"esquilo":false},
  {"events":["lasagna","sorvetem","trabalhou","árvore"],"esquilo":false},
  {"events":["couve-flor","amendoim","escovou os dentes","pedalou","trabalhou"],"esquilo":false},
  {"events":["pizza","escovou os dentes","running","trabalhou"],"esquilo":false},
  {"events":["alface","escovou os dentes","trabalhou"],"esquilo":false},
  {"events":["pão","escovou os dentes","television","final de semana"],"esquilo":false},
  {"events":["couve-flor","amendoim","escovou os dentes","final de semana"],"esquilo":false}
];

// This makes sure the data is exported in node.js —
// // `require('./path/to/04_data.js')` will get you the array.
// if (typeof module != "undefined" && module.exports)
//   module.exports = JOURNAL;
